-- Dash de Carga - schema limpo para Supabase
-- Execute no SQL Editor do Supabase.
-- Este script cobre as tabelas usadas pelo dashboard atual e pelo worker.

begin;

-- =========================================================
-- TABELA PRINCIPAL: REPORTE DE CARGAS
-- =========================================================
create table if not exists public.reporte_carga (
  id bigint generated by default as identity primary key,
  dt text not null,
  transportadora text,
  grade_carregamento text,
  fim_carregamento text,
  hora_chegada text default ''::text,
  status text default 'AG CHEGADA'::text,
  tipo text,
  toneladas text,
  agenda text,
  local_cd text,
  dia_ref text,
  data_ref text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  reagendada boolean default false,
  tipo_operacao text,
  descricao_documento text,
  nome_cliente_fornecedor text
);

alter table public.reporte_carga
  add column if not exists tipo_operacao text;

alter table public.reporte_carga
  add column if not exists descricao_documento text;

alter table public.reporte_carga
  add column if not exists nome_cliente_fornecedor text;

create unique index if not exists ux_reporte_carga_dt_data_ref
  on public.reporte_carga (dt, data_ref);

create index if not exists ix_reporte_carga_data_ref
  on public.reporte_carga (data_ref);

create index if not exists ix_reporte_carga_status
  on public.reporte_carga (status);

create index if not exists ix_reporte_carga_dt
  on public.reporte_carga (dt);

-- =========================================================
-- HISTORICO DE STATUS POR DT
-- =========================================================
create table if not exists public.reporte_carga_status_hist (
  id bigint generated by default as identity primary key,
  dt text not null,
  data_ref text not null,
  status text not null,
  transportadora text,
  hora_chegada text,
  changed_at timestamptz not null default now(),
  source text not null default 'SYSTEM'
);

create index if not exists ix_reporte_carga_status_hist_dt_ref_changed
  on public.reporte_carga_status_hist (dt, data_ref, changed_at desc);

create or replace function public.fn_reporte_carga_audit_status()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.reporte_carga_status_hist
      (dt, data_ref, status, transportadora, hora_chegada, source)
    values
      (new.dt, new.data_ref, coalesce(new.status, 'AG CHEGADA'), new.transportadora, coalesce(new.hora_chegada, ''), 'INSERT');
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if coalesce(old.status, '') is distinct from coalesce(new.status, '')
       or coalesce(old.hora_chegada, '') is distinct from coalesce(new.hora_chegada, '') then
      insert into public.reporte_carga_status_hist
        (dt, data_ref, status, transportadora, hora_chegada, source)
      values
        (new.dt, new.data_ref, coalesce(new.status, 'AG CHEGADA'), new.transportadora, coalesce(new.hora_chegada, ''), 'UPDATE');
    end if;
    return new;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_reporte_carga_audit_status on public.reporte_carga;
create trigger trg_reporte_carga_audit_status
after insert or update on public.reporte_carga
for each row execute function public.fn_reporte_carga_audit_status();

-- =========================================================
-- MATERIAIS DA DT
-- =========================================================
create table if not exists public.reporte_materiais (
  id bigint generated by default as identity primary key,
  dt text not null,
  data_ref text not null,
  material text,
  quantidade text,
  observacao text,
  ordem integer default 0,
  paletizacao text,
  created_at timestamptz default now()
);

create index if not exists ix_reporte_materiais_dt_ref
  on public.reporte_materiais (dt, data_ref);

-- =========================================================
-- LOGS LEGADOS / FALLBACK
-- =========================================================
create table if not exists public.reporte_logs (
  id bigint generated by default as identity primary key,
  dt text not null,
  data_ref text not null,
  status text not null,
  transportadora text,
  created_at timestamptz default now()
);

create index if not exists ix_reporte_logs_dt_ref_created
  on public.reporte_logs (dt, data_ref, created_at desc);

create table if not exists public.dt_logs (
  id bigint generated by default as identity primary key,
  dt text not null,
  data_ref text not null,
  hora_evento timestamptz not null default now(),
  event_type text not null,
  status_before text,
  status_after text,
  transportadora text,
  grade_carregamento text,
  fim_carregamento text,
  source text,
  payload jsonb
);

create index if not exists ix_dt_logs_dt_ref_hora
  on public.dt_logs (dt, data_ref, hora_evento desc);

create index if not exists ix_dt_logs_event_type
  on public.dt_logs (event_type);

-- =========================================================
-- SNAPSHOTS DO DASHBOARD
-- =========================================================
create table if not exists public.grade_snapshots (
  id bigint generated by default as identity primary key,
  data_ref text not null,
  data_operacao date,
  snapshot_at timestamptz not null default now(),
  source text not null default 'DASHBOARD',
  evento text,
  planejado_suzano_kg numeric,
  nossa_grade_kg numeric,
  realizado_kg numeric,
  pendente_kg numeric,
  dts_total integer,
  dts_abertas integer,
  dts_expedidas integer,
  dts_no_show integer,
  dts_recusadas integer,
  detalhes jsonb
);

create index if not exists ix_grade_snapshots_data_ref_snapshot_at
  on public.grade_snapshots (data_ref, snapshot_at desc);

create table if not exists public.planejamento_suzano_snapshots (
  id bigint generated by default as identity primary key,
  data_ref text not null,
  data_operacao date,
  planejado_suzano_kg numeric,
  dts_total integer,
  source text not null default 'DASHBOARD',
  observacao text,
  detalhes jsonb,
  snapshot_at timestamptz not null default now()
);

create index if not exists ix_planejamento_suzano_snapshots_data_ref_snapshot_at
  on public.planejamento_suzano_snapshots (data_ref, snapshot_at desc);

create table if not exists public.reportes_diarios (
  id bigint generated by default as identity primary key,
  data_ref text not null,
  data_operacao date,
  tipo text,
  hora_reporte timestamptz default now(),
  planejado_suzano_kg numeric,
  grade_atual_kg numeric,
  realizado_kg numeric,
  pendente_kg numeric,
  variacao_suzano_kg numeric,
  variacao_grade_kg numeric,
  dts_expedidas integer,
  dts_no_show integer,
  dts_recusadas integer,
  resumo jsonb
);

create index if not exists ix_reportes_diarios_data_ref_hora
  on public.reportes_diarios (data_ref, hora_reporte desc);

-- =========================================================
-- CONFIGURACAO DO ENVIO DE E-MAIL
-- =========================================================
create table if not exists public.report_delivery_config (
  id text primary key default 'default',
  email_provider text not null default 'zoho',
  email_from text not null default '',
  email_to text[] not null default '{}',
  email_cc text[] not null default '{}',
  auto_email_enabled boolean not null default true,
  auto_email_interval_minutes integer not null default 60,
  report_inicial time not null default '00:00:00',
  report_final time not null default '11:59:59',
  send_next_day_at_final boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.report_delivery_config (id)
values ('default')
on conflict (id) do nothing;

-- =========================================================
-- RLS POLICIES
-- =========================================================
alter table public.reporte_carga enable row level security;
alter table public.reporte_carga_status_hist enable row level security;
alter table public.reporte_materiais enable row level security;
alter table public.reporte_logs enable row level security;
alter table public.dt_logs enable row level security;
alter table public.grade_snapshots enable row level security;
alter table public.planejamento_suzano_snapshots enable row level security;
alter table public.reportes_diarios enable row level security;
alter table public.report_delivery_config enable row level security;

drop policy if exists "public_select_reporte_carga" on public.reporte_carga;
create policy "public_select_reporte_carga"
  on public.reporte_carga
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_reporte_carga" on public.reporte_carga;
create policy "public_insert_reporte_carga"
  on public.reporte_carga
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_update_reporte_carga" on public.reporte_carga;
create policy "public_update_reporte_carga"
  on public.reporte_carga
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "public_delete_reporte_carga" on public.reporte_carga;
create policy "public_delete_reporte_carga"
  on public.reporte_carga
  for delete
  to anon, authenticated
  using (true);

drop policy if exists "public_select_reporte_carga_status_hist" on public.reporte_carga_status_hist;
create policy "public_select_reporte_carga_status_hist"
  on public.reporte_carga_status_hist
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_reporte_carga_status_hist" on public.reporte_carga_status_hist;
create policy "public_insert_reporte_carga_status_hist"
  on public.reporte_carga_status_hist
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_select_reporte_materiais" on public.reporte_materiais;
create policy "public_select_reporte_materiais"
  on public.reporte_materiais
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_reporte_materiais" on public.reporte_materiais;
create policy "public_insert_reporte_materiais"
  on public.reporte_materiais
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_update_reporte_materiais" on public.reporte_materiais;
create policy "public_update_reporte_materiais"
  on public.reporte_materiais
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "public_delete_reporte_materiais" on public.reporte_materiais;
create policy "public_delete_reporte_materiais"
  on public.reporte_materiais
  for delete
  to anon, authenticated
  using (true);

drop policy if exists "public_select_reporte_logs" on public.reporte_logs;
create policy "public_select_reporte_logs"
  on public.reporte_logs
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_reporte_logs" on public.reporte_logs;
create policy "public_insert_reporte_logs"
  on public.reporte_logs
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_select_dt_logs" on public.dt_logs;
create policy "public_select_dt_logs"
  on public.dt_logs
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_dt_logs" on public.dt_logs;
create policy "public_insert_dt_logs"
  on public.dt_logs
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_select_grade_snapshots" on public.grade_snapshots;
create policy "public_select_grade_snapshots"
  on public.grade_snapshots
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_grade_snapshots" on public.grade_snapshots;
create policy "public_insert_grade_snapshots"
  on public.grade_snapshots
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_select_planejamento_suzano_snapshots" on public.planejamento_suzano_snapshots;
create policy "public_select_planejamento_suzano_snapshots"
  on public.planejamento_suzano_snapshots
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_planejamento_suzano_snapshots" on public.planejamento_suzano_snapshots;
create policy "public_insert_planejamento_suzano_snapshots"
  on public.planejamento_suzano_snapshots
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_select_reportes_diarios" on public.reportes_diarios;
create policy "public_select_reportes_diarios"
  on public.reportes_diarios
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_reportes_diarios" on public.reportes_diarios;
create policy "public_insert_reportes_diarios"
  on public.reportes_diarios
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_select_report_delivery_config" on public.report_delivery_config;
create policy "public_select_report_delivery_config"
  on public.report_delivery_config
  for select
  to anon, authenticated
  using (true);

drop policy if exists "public_insert_report_delivery_config" on public.report_delivery_config;
create policy "public_insert_report_delivery_config"
  on public.report_delivery_config
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "public_update_report_delivery_config" on public.report_delivery_config;
create policy "public_update_report_delivery_config"
  on public.report_delivery_config
  for update
  to anon, authenticated
  using (true)
  with check (true);

commit;
