-- =========================================================
-- MIGRAÇÃO: adiciona colunas que faltam em reporte_carga
-- Execute este script no Supabase: SQL Editor → Run
-- =========================================================

-- 1. Adiciona tipo_operacao (TRANSFERÊNCIA / VENDA NORMAL)
ALTER TABLE public.reporte_carga
  ADD COLUMN IF NOT EXISTS tipo_operacao text;

-- 2. Adiciona descricao_documento (coluna J da ZLES002:
--    "Venda Normal", "Remessa p/ transf. (filial)", etc.)
ALTER TABLE public.reporte_carga
  ADD COLUMN IF NOT EXISTS descricao_documento text;

-- 3. Índice de performance para as consultas por data_ref + status
CREATE INDEX IF NOT EXISTS ix_reporte_carga_data_ref
  ON public.reporte_carga (data_ref);

CREATE INDEX IF NOT EXISTS ix_reporte_carga_status
  ON public.reporte_carga (status);

-- 4. Tabela de histórico de status (caso ainda não exista)
CREATE TABLE IF NOT EXISTS public.reporte_carga_status_hist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dt text NOT NULL,
  data_ref text NOT NULL,
  status text NOT NULL,
  transportadora text,
  hora_chegada text,
  changed_at timestamptz NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'SYSTEM'
);

-- 5. Confirma
SELECT
  column_name,
  data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name   = 'reporte_carga'
ORDER BY ordinal_position;
