-- Operational history layer for Dash de Carga
-- Run in Supabase SQL Editor. Safe to run more than once.

begin;

-- ---------------------------------------------------------------------
-- 1) Bring current-state tables up to the fields the dashboard now uses.
-- ---------------------------------------------------------------------
alter table if exists public.reporte_carga
  add column if not exists n_portaria text,
  add column if not exists peso_liquido text,
  add column if not exists paletizacao text,
  add column if not exists centro text,
  add column if not exists updated_at timestamptz default now(),
  add column if not exists source text default 'DASHBOARD';

alter table if exists public.reporte_materiais
  add column if not exists paletizacao text,
  add column if not exists updated_at timestamptz default now();

-- Keep one active row per DT/day in the current state table.
with ranked as (
  select id,
         row_number() over (
           partition by dt, data_ref
           order by updated_at desc nulls last, created_at desc nulls last, id desc
         ) as rn
  from public.reporte_carga
)
delete from public.reporte_carga rc
using ranked r
where rc.id = r.id
  and r.rn > 1;

create unique index if not exists ux_reporte_carga_dt_data_ref
  on public.reporte_carga (dt, data_ref);

create index if not exists ix_reporte_carga_data_ref
  on public.reporte_carga (data_ref);

create index if not exists ix_reporte_carga_status
  on public.reporte_carga (status);

create index if not exists ix_reporte_carga_fim
  on public.reporte_carga (fim_carregamento);

-- Smart material upsert support. Do not delete missing materials by default.
with ranked as (
  select id,
         row_number() over (
           partition by dt, data_ref, material
           order by updated_at desc nulls last, created_at desc nulls last, id desc
         ) as rn
  from public.reporte_materiais
  where material is not null and material <> ''
)
delete from public.reporte_materiais rm
using ranked r
where rm.id = r.id
  and r.rn > 1;

create unique index if not exists ux_reporte_materiais_dt_data_ref_material
  on public.reporte_materiais (dt, data_ref, material)
  where material is not null and material <> '';

create index if not exists ix_reporte_materiais_dt_data_ref
  on public.reporte_materiais (dt, data_ref);

-- ---------------------------------------------------------------------
-- 2) Weight parser used by snapshots/reportes.
--    Handles examples like: 9202, 9.202, 9202,50, 1.493,51.
-- ---------------------------------------------------------------------
create or replace function public.fn_parse_peso_kg(raw text)
returns numeric
language plpgsql
immutable
as $$
declare
  s text;
  n numeric;
begin
  s := trim(coalesce(raw, ''));
  if s = '' then
    return 0;
  end if;

  s := regexp_replace(s, '\s+', '', 'g');

  if position(',' in s) > 0 and position('.' in s) > 0 then
    if strpos(reverse(s), ',') < strpos(reverse(s), '.') then
      s := replace(replace(s, '.', ''), ',', '.');
    else
      s := replace(s, ',', '');
    end if;
  elsif position(',' in s) > 0 then
    s := replace(replace(s, '.', ''), ',', '.');
  elsif s ~ '^\d{1,3}(\.\d{3})+$' then
    s := replace(s, '.', '');
  end if;

  s := regexp_replace(s, '[^0-9\.-]', '', 'g');
  if s = '' or s = '-' or s = '.' then
    return 0;
  end if;

  n := s::numeric;
  return floor(n);
exception when others then
  return 0;
end;
$$;

-- ---------------------------------------------------------------------
-- 3) Immutable DT event history.
-- ---------------------------------------------------------------------
create table if not exists public.dt_logs (
  id bigint generated by default as identity primary key,
  dt text not null,
  data_ref text not null,
  event_type text not null,
  status_before text,
  status_after text,
  toneladas numeric default 0,
  tipo_carga text,
  tipo_operacao text,
  turno text,
  transportadora text,
  grade_carregamento text,
  fim_carregamento text,
  hora_chegada text,
  n_portaria text,
  data_operacao date,
  hora_evento timestamptz not null default now(),
  usuario text default current_user,
  source text not null default 'SYSTEM',
  payload jsonb not null default '{}'::jsonb
);

create index if not exists ix_dt_logs_data_operacao_hora
  on public.dt_logs (data_operacao, hora_evento desc);

create index if not exists ix_dt_logs_dt_data_ref_hora
  on public.dt_logs (dt, data_ref, hora_evento desc);

create index if not exists ix_dt_logs_event_type
  on public.dt_logs (event_type);

create or replace function public.fn_reporte_carga_event_log()
returns trigger
language plpgsql
as $$
declare
  event_name text;
  ref_text text;
  ref_date date;
  row_new public.reporte_carga%rowtype;
  row_old public.reporte_carga%rowtype;
begin
  if tg_op = 'INSERT' then
    event_name := 'DT_CREATED';
    row_new := new;
    ref_text := coalesce(new.data_ref, '');
  elsif tg_op = 'UPDATE' then
    if to_jsonb(old) = to_jsonb(new) then
      return new;
    end if;
    event_name := case
      when coalesce(old.status,'') is distinct from coalesce(new.status,'') then 'STATUS_CHANGED'
      when coalesce(old.grade_carregamento,'') is distinct from coalesce(new.grade_carregamento,'')
        or coalesce(old.fim_carregamento,'') is distinct from coalesce(new.fim_carregamento,'') then 'GRADE_CHANGED'
      when coalesce(old.peso_liquido,'') is distinct from coalesce(new.peso_liquido,'')
        or coalesce(old.toneladas,'') is distinct from coalesce(new.toneladas,'') then 'WEIGHT_CHANGED'
      else 'DT_UPDATED'
    end;
    row_new := new;
    row_old := old;
    ref_text := coalesce(new.data_ref, old.data_ref, '');
  elsif tg_op = 'DELETE' then
    event_name := 'DT_REMOVED_FROM_CURRENT';
    row_old := old;
    ref_text := coalesce(old.data_ref, '');
  end if;

  begin
    ref_date := to_date(ref_text, 'DD/MM/YYYY');
  exception when others then
    ref_date := null;
  end;

  insert into public.dt_logs (
    dt, data_ref, event_type,
    status_before, status_after,
    toneladas, tipo_carga, tipo_operacao, turno,
    transportadora, grade_carregamento, fim_carregamento,
    hora_chegada, n_portaria, data_operacao, source, payload
  )
  values (
    coalesce(row_new.dt, row_old.dt),
    ref_text,
    event_name,
    row_old.status,
    row_new.status,
    public.fn_parse_peso_kg(coalesce(row_new.peso_liquido, row_new.toneladas, row_old.peso_liquido, row_old.toneladas)),
    coalesce(row_new.paletizacao, row_old.paletizacao),
    coalesce(row_new.tipo_operacao, row_old.tipo_operacao),
    case
      when coalesce(row_new.fim_carregamento, row_old.fim_carregamento, '') ~ '^\d{2}/\d{2}/\d{4}\s+\d{2}:\d{2}' then
        case
          when extract(hour from to_timestamp(coalesce(row_new.fim_carregamento, row_old.fim_carregamento), 'DD/MM/YYYY HH24:MI')) between 7 and 14 then 'T1'
          when extract(hour from to_timestamp(coalesce(row_new.fim_carregamento, row_old.fim_carregamento), 'DD/MM/YYYY HH24:MI')) between 15 and 22 then 'T2'
          else 'T3'
        end
      else null
    end,
    coalesce(row_new.transportadora, row_old.transportadora),
    coalesce(row_new.grade_carregamento, row_old.grade_carregamento),
    coalesce(row_new.fim_carregamento, row_old.fim_carregamento),
    coalesce(row_new.hora_chegada, row_old.hora_chegada),
    coalesce(row_new.n_portaria, row_old.n_portaria),
    ref_date,
    coalesce(row_new.source, row_old.source, 'DASHBOARD'),
    jsonb_build_object('old', to_jsonb(row_old), 'new', to_jsonb(row_new))
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_reporte_carga_event_log on public.reporte_carga;
create trigger trg_reporte_carga_event_log
after insert or update or delete on public.reporte_carga
for each row execute function public.fn_reporte_carga_event_log();

-- Keep the existing status history table, but ensure it exists.
create table if not exists public.reporte_carga_status_hist (
  id bigint generated by default as identity primary key,
  dt text not null,
  data_ref text not null,
  status text not null,
  transportadora text,
  hora_chegada text,
  changed_at timestamptz not null default now(),
  source text not null default 'SYSTEM'
);

create index if not exists ix_hist_dt_data_ref_changed
  on public.reporte_carga_status_hist (dt, data_ref, changed_at desc);

-- ---------------------------------------------------------------------
-- 4) Temporal grade snapshots.
-- ---------------------------------------------------------------------
create table if not exists public.grade_snapshots (
  id bigint generated by default as identity primary key,
  data_ref text not null,
  data_operacao date,
  snapshot_at timestamptz not null default now(),
  source text not null default 'SYSTEM',
  evento text,
  planejado_suzano_kg numeric,
  nossa_grade_kg numeric not null default 0,
  realizado_kg numeric not null default 0,
  pendente_kg numeric not null default 0,
  dts_total integer not null default 0,
  dts_abertas integer not null default 0,
  dts_expedidas integer not null default 0,
  dts_no_show integer not null default 0,
  dts_recusadas integer not null default 0,
  detalhes jsonb not null default '{}'::jsonb
);

create index if not exists ix_grade_snapshots_data_ref_at
  on public.grade_snapshots (data_ref, snapshot_at);

create index if not exists ix_grade_snapshots_data_operacao_at
  on public.grade_snapshots (data_operacao, snapshot_at);

create or replace function public.fn_create_grade_snapshot(
  p_data_ref text,
  p_source text default 'DASHBOARD',
  p_evento text default null,
  p_planejado_suzano_kg numeric default null
)
returns bigint
language plpgsql
as $$
declare
  new_id bigint;
  ref_date date;
begin
  begin
    ref_date := to_date(p_data_ref, 'DD/MM/YYYY');
  exception when others then
    ref_date := null;
  end;

  insert into public.grade_snapshots (
    data_ref, data_operacao, source, evento, planejado_suzano_kg,
    nossa_grade_kg, realizado_kg, pendente_kg,
    dts_total, dts_abertas, dts_expedidas, dts_no_show, dts_recusadas,
    detalhes
  )
  select
    p_data_ref,
    ref_date,
    coalesce(p_source, 'DASHBOARD'),
    p_evento,
    p_planejado_suzano_kg,
    coalesce(sum(public.fn_parse_peso_kg(coalesce(peso_liquido, toneladas, '0')))
      filter (where coalesce(status,'') not in ('NO SHOW','VEICULO RECUSADO')), 0),
    coalesce(sum(public.fn_parse_peso_kg(coalesce(peso_liquido, toneladas, '0')))
      filter (where coalesce(status,'') in ('EXPEDIDO','EM FATURAMENTO')), 0),
    greatest(
      coalesce(sum(public.fn_parse_peso_kg(coalesce(peso_liquido, toneladas, '0')))
        filter (where coalesce(status,'') not in ('NO SHOW','VEICULO RECUSADO')), 0)
      -
      coalesce(sum(public.fn_parse_peso_kg(coalesce(peso_liquido, toneladas, '0')))
        filter (where coalesce(status,'') in ('EXPEDIDO','EM FATURAMENTO')), 0),
      0
    ),
    count(*)::integer,
    count(*) filter (where coalesce(status,'') not in ('EXPEDIDO','NO SHOW','VEICULO RECUSADO'))::integer,
    count(*) filter (where coalesce(status,'') = 'EXPEDIDO')::integer,
    count(*) filter (where coalesce(status,'') = 'NO SHOW')::integer,
    count(*) filter (where coalesce(status,'') = 'VEICULO RECUSADO')::integer,
    jsonb_build_object(
      'por_status', coalesce((
        select jsonb_object_agg(status_key, qtd)
        from (
          select coalesce(status,'SEM STATUS') as status_key, count(*) as qtd
          from public.reporte_carga
          where data_ref = p_data_ref
          group by coalesce(status,'SEM STATUS')
        ) s
      ), '{}'::jsonb),
      'por_operacao', coalesce((
        select jsonb_object_agg(op_key, kg)
        from (
          select coalesce(tipo_operacao,'SEM OPERACAO') as op_key,
                 sum(public.fn_parse_peso_kg(coalesce(peso_liquido, toneladas, '0'))) as kg
          from public.reporte_carga
          where data_ref = p_data_ref
            and coalesce(status,'') not in ('NO SHOW','VEICULO RECUSADO')
          group by coalesce(tipo_operacao,'SEM OPERACAO')
        ) o
      ), '{}'::jsonb)
    )
  from public.reporte_carga
  where data_ref = p_data_ref
  returning id into new_id;

  return new_id;
end;
$$;

-- ---------------------------------------------------------------------
-- 5) Saved reportes.
-- ---------------------------------------------------------------------
create table if not exists public.reportes_diarios (
  id bigint generated by default as identity primary key,
  data_ref text not null,
  data_operacao date,
  tipo text not null check (tipo in ('INICIAL','PARCIAL','FINAL','MANUAL')),
  hora_reporte timestamptz not null default now(),
  planejado_suzano_kg numeric,
  grade_atual_kg numeric not null default 0,
  realizado_kg numeric not null default 0,
  pendente_kg numeric not null default 0,
  variacao_suzano_kg numeric,
  variacao_grade_kg numeric,
  dts_expedidas integer not null default 0,
  dts_no_show integer not null default 0,
  dts_recusadas integer not null default 0,
  snapshot_id bigint references public.grade_snapshots(id),
  resumo jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by text default current_user
);

create index if not exists ix_reportes_diarios_data_ref_hora
  on public.reportes_diarios (data_ref, hora_reporte desc);

create index if not exists ix_reportes_diarios_tipo
  on public.reportes_diarios (tipo);

-- ---------------------------------------------------------------------
-- 6) Optional explicit Suzano planning timeline.
-- ---------------------------------------------------------------------
create table if not exists public.planejamento_suzano_snapshots (
  id bigint generated by default as identity primary key,
  data_ref text not null,
  data_operacao date,
  snapshot_at timestamptz not null default now(),
  planejado_suzano_kg numeric not null default 0,
  dts_total integer not null default 0,
  source text not null default 'SUZANO',
  observacao text,
  detalhes jsonb not null default '{}'::jsonb
);

create index if not exists ix_planejamento_suzano_data_ref_at
  on public.planejamento_suzano_snapshots (data_ref, snapshot_at);

commit;
