-- Schema sync for dashboard + Supabase integration
-- Project: pwjatxqtkvwcmzmjjvbi

begin;

-- Ensure required columns used by UI exist
alter table if exists public.reporte_carga
  add column if not exists n_portaria text,
  add column if not exists peso_liquido text,
  add column if not exists paletizacao text,
  add column if not exists tipo_operacao text,
  add column if not exists descricao_documento text,
  add column if not exists reagendada boolean default false,
  add column if not exists updated_at timestamptz default now();

-- Remove duplicated DT/date rows before unique index
with ranked as (
  select id,
         row_number() over (
           partition by dt, data_ref
           order by updated_at desc nulls last, id desc
         ) as rn
  from public.reporte_carga
)
delete from public.reporte_carga rc
using ranked r
where rc.id = r.id
  and r.rn > 1;

create unique index if not exists ux_reporte_carga_dt_data_ref
  on public.reporte_carga (dt, data_ref);

create index if not exists ix_reporte_carga_data_ref
  on public.reporte_carga (data_ref);

create index if not exists ix_reporte_carga_status
  on public.reporte_carga (status);

alter table if exists public.reporte_materiais
  add column if not exists paletizacao text;

create table if not exists public.reporte_carga_status_hist (
  id bigint generated by default as identity primary key,
  dt text not null,
  data_ref text not null,
  status text not null,
  transportadora text,
  hora_chegada text,
  changed_at timestamptz not null default now(),
  source text not null default 'SYSTEM'
);

create index if not exists ix_hist_dt_data_ref_changed
  on public.reporte_carga_status_hist (dt, data_ref, changed_at desc);

create or replace function public.fn_reporte_carga_audit_status()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.reporte_carga_status_hist
      (dt, data_ref, status, transportadora, hora_chegada, source)
    values
      (new.dt, new.data_ref, coalesce(new.status, 'AG CHEGADA'), new.transportadora, coalesce(new.hora_chegada,''), 'INSERT');
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if coalesce(old.status,'') is distinct from coalesce(new.status,'')
       or coalesce(old.hora_chegada,'') is distinct from coalesce(new.hora_chegada,'') then
      insert into public.reporte_carga_status_hist
        (dt, data_ref, status, transportadora, hora_chegada, source)
      values
        (new.dt, new.data_ref, coalesce(new.status, 'AG CHEGADA'), new.transportadora, coalesce(new.hora_chegada,''), 'UPDATE');
    end if;
    return new;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_reporte_carga_audit_status on public.reporte_carga;
create trigger trg_reporte_carga_audit_status
after insert or update on public.reporte_carga
for each row execute function public.fn_reporte_carga_audit_status();

commit;
