begin;

-- Colunas que o dashboard atual ja tenta ler/gravar.
alter table public.reporte_carga add column if not exists n_portaria text default '';
alter table public.reporte_carga add column if not exists peso_liquido text default '';
alter table public.reporte_carga add column if not exists centro text default '';
alter table public.reporte_carga add column if not exists paletizacao text default '';
alter table public.reporte_carga add column if not exists doca_null boolean default false;
alter table public.reporte_carga add column if not exists source text default 'DASHBOARD';

create table if not exists public.oracle_job_status (
  id bigint generated by default as identity primary key,
  run_id text not null unique,
  status text not null default 'running',
  stage text,
  message text,
  grade_count integer not null default 0,
  zles_count integer not null default 0,
  material_count integer not null default 0,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  details jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists ix_oracle_job_status_updated
  on public.oracle_job_status (updated_at desc);

create table if not exists public.oracle_report_images (
  id bigint generated by default as identity primary key,
  run_id text,
  data_ref text not null,
  shift text,
  content_type text not null default 'image/png',
  image_base64 text not null,
  created_at timestamptz not null default now()
);

create index if not exists ix_oracle_report_images_ref_created
  on public.oracle_report_images (data_ref, created_at desc);

alter table public.oracle_job_status enable row level security;
alter table public.oracle_report_images enable row level security;

drop policy if exists "public_select_oracle_job_status" on public.oracle_job_status;
create policy "public_select_oracle_job_status"
  on public.oracle_job_status
  for select
  to anon, authenticated
  using (true);

-- Escritas ficam exclusivas ao Worker, que usa a service role.

commit;
